### ISSUE TITLE
chassis v1.76 zipkin-go-opentracing 版本问题

### ISSUE THREAD

**Issue by superufo** [go-chassis/go-chassis-examples#9]
当使用chassis v1.76 运行本例的时候，会发现 zipkin-go-opentracing 必须为小于等于 v0.3.5

go get github.com/openzipkin-contrib/zipkin-go-opentracing@v0.3.5

**Comment by tianxiaoliang** [comment]
请问是解决了？


superufo <notifications@github.com> 于 2020年5月9日周六 16:53写道：
